//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Role = newRoleTable("public", "role", "")

type roleTable struct {
	postgres.Table

	// Columns
	RoleID          postgres.ColumnInteger
	RoleName        postgres.ColumnString
	RoleDescription postgres.ColumnString
	Version         postgres.ColumnInteger
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type RoleTable struct {
	roleTable

	EXCLUDED roleTable
}

// AS creates new RoleTable with assigned alias
func (a RoleTable) AS(alias string) *RoleTable {
	return newRoleTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RoleTable with assigned schema name
func (a RoleTable) FromSchema(schemaName string) *RoleTable {
	return newRoleTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RoleTable with assigned table prefix
func (a RoleTable) WithPrefix(prefix string) *RoleTable {
	return newRoleTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RoleTable with assigned table suffix
func (a RoleTable) WithSuffix(suffix string) *RoleTable {
	return newRoleTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRoleTable(schemaName, tableName, alias string) *RoleTable {
	return &RoleTable{
		roleTable: newRoleTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newRoleTableImpl("", "excluded", ""),
	}
}

func newRoleTableImpl(schemaName, tableName, alias string) roleTable {
	var (
		RoleIDColumn          = postgres.IntegerColumn("role_id")
		RoleNameColumn        = postgres.StringColumn("role_name")
		RoleDescriptionColumn = postgres.StringColumn("role_description")
		VersionColumn         = postgres.IntegerColumn("version")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{RoleIDColumn, RoleNameColumn, RoleDescriptionColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{RoleNameColumn, RoleDescriptionColumn, VersionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return roleTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		RoleID:          RoleIDColumn,
		RoleName:        RoleNameColumn,
		RoleDescription: RoleDescriptionColumn,
		Version:         VersionColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
