BEGIN;
ALTER TABLE user_auth
ALTER created_at SET DATA TYPE TIMESTAMPTZ,
ALTER updated_at SET DATA TYPE TIMESTAMPTZ,
ALTER OTP_created_at SET DATA TYPE TIMESTAMPTZ,
ALTER expires_at SET DATA TYPE TIMESTAMPTZ;
COMMIT;