//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Action struct {
	ActionID          int32 `sql:"primary_key"`
	ActionName        string
	ActionCode        string
	ActionDescription *string
	PermissionID      *int32
	Version           int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
