//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AgoraWebhookEvents struct {
	ID          int32 `sql:"primary_key"`
	EventType   string
	EventTime   time.Time
	UID         *string
	ChannelName *string
	SessionID   *string
	AppID       string
	Payload     string
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}
