//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Consultant struct {
	ConsultantID     uuid.UUID `sql:"primary_key"`
	UserID           uuid.UUID
	Expertise        *string
	State            string
	Version          *int32
	ChatChannel      *string
	CallChannel      *string
	LiveChannel      *string
	VideoCallChannel *string
	CreatedAt        *time.Time
	UpdatedAt        *time.Time
}
