//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Consultation struct {
	ConsultationID       uuid.UUID `sql:"primary_key"`
	UserID               uuid.UUID
	ConsultantID         uuid.UUID
	SessionID            *uuid.UUID
	ConsultationTimeSecs *int32
	ConsultationType     string
	ConsultationState    string
	UserWaitTimeSecs     *int32
	AgoraChannel         *string
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
}
