//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserAuth struct {
	ID               uuid.UUID `sql:"primary_key"`
	UserID           uuid.UUID
	SessionID        uuid.UUID
	JwtTokenHash     string
	RefreshTokenHash string
	DeviceDetails    *string
	Otp              int32
	OtpCreatedAt     time.Time
	OtpValiditySecs  int32
	OtpAttempts      int32
	PhoneNumber      string
	CreatedAt        time.Time
	ExpiresAt        time.Time
	UpdatedAt        time.Time
}
